### ISSUE TITLE
Empty cache when saving singleton or collection

### ISSUE THREAD

**Issue by natemate90** [agentejo/SimpleResponseCache#2]
This is an awesome plugin, saves a lot of headaches and makes cockpit blazingly fast. Currently, I'm always manually clearing the cache in the settings / system. Is this the only way to do that? It would be nice if somehow the cache could be cleared automatically when updating a collection / singleton. I can live with it, but would be nice to have

**Comment by gokaybiz** [comment]
https://github.com/agentejo/SimpleResponseCache/blob/35c903844b1dcf87c650f6873c366869e0e4dc8a/bootstrap.php#L26
Doesn't it work?

**Comment by natemate90** [comment]
I had an outdated version. Many thanks!
